name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Android 빌드 (Ubuntu 환경)
  android-build:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행
    strategy:
      matrix:
        flutter-version: ['3.29.0']  # 사용할 Flutter 버전
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Android)
        run: flutter build apk --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk


  # iOS 빌드 (macOS 환경)
   ios-build:
    runs-on: macos-latest
    strategy:
      matrix:
        flutter-version: ['3.29.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (Archive)
        run: flutter build ipa --release --no-codesign

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/archive/ \
            -exportOptionsPlist ios/exportOptions.plist

      - name: Check if IPA exists
        run: |
          if [ ! -f build/ios/archive/Runner.ipa ]; then
            echo "IPA not found!"
            exit 1
          fi

      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-release-ipa
          path: build/ios/archive/Runner.ipa