name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
  # iOS 빌드 (macOS 환경)
  ios-build:
    runs-on: macos-latest  # macOS 환경에서 실행
    strategy:
      matrix:
        flutter-version: ['3.29.0']  # 사용할 Flutter 버전
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (Release)
        run: flutter build ios --release --no-codesign
